### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by jamesjer** [ocsigen/reactiveData#28]
The license of this project is unclear.  The opam file says:
```
license: "LGPL-3.0 with OCaml linking exception"
```

However, the LICENSE file contains the text of LGPL 2.1, not 3.0.  Furthermore, the headers of both `src/reactiveData.ml` and `src/reactiveData.mli` claim that the license is LGPL-2.1-or-later with the OCaml linking exception.

Is the license LGPL 2.1 or 3.0?  Is "any later version" okay, or not?  Thank you.

**Comment by jamesjer** [comment]
Also, the address for the FSF given in the LICENSE file has been wrong for 16 years now.  It would be good to refresh the text of the LICENSE file from the FSF: 
- https://www.gnu.org/licenses/old-licenses/lgpl-2.1.html
- https://www.gnu.org/licenses/lgpl-3.0.html

**Comment by hhugo** [comment]
I've updated the license file to LGPL 3. Sorry for the delay.
