### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by Drup** [ocsigen/reactiveData#6]
There is a bugfix on singleton_s that is not in the last released version, can you make a new one ? the bugfix is needed for the eliom tutorial on reactive nodes ....

**Comment by Drup** [comment]
ping ? "a few days" ?!

**Comment by vbmithr** [comment]
Ping. Release please.

**Comment by j0sh** [comment]
Ping for a new release. The issue with singleton_s is causing problems in the wild: https://github.com/ocsigen/js_of_ocaml/issues/366

**Comment by vasilisp** [comment]
We need a release to go with the new Eliom. I guess we can release once the documentation (#14) goes through.

**Comment by Drup** [comment]
https://github.com/ocaml/opam-repository/pull/5488
